// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/consignment.proto

package consignment

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 货轮承运的一批货物
type Consignment struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description          string       `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Weight               int32        `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Containers           []*Contanier `protobuf:"bytes,4,rep,name=containers,proto3" json:"containers,omitempty"`
	VesselId             string       `protobuf:"bytes,5,opt,name=vessel_id,json=vesselId,proto3" json:"vessel_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Consignment) Reset()         { *m = Consignment{} }
func (m *Consignment) String() string { return proto.CompactTextString(m) }
func (*Consignment) ProtoMessage()    {}
func (*Consignment) Descriptor() ([]byte, []int) {
	return fileDescriptor_774f0b29a0c4f8e9, []int{0}
}

func (m *Consignment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consignment.Unmarshal(m, b)
}
func (m *Consignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consignment.Marshal(b, m, deterministic)
}
func (m *Consignment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consignment.Merge(m, src)
}
func (m *Consignment) XXX_Size() int {
	return xxx_messageInfo_Consignment.Size(m)
}
func (m *Consignment) XXX_DiscardUnknown() {
	xxx_messageInfo_Consignment.DiscardUnknown(m)
}

var xxx_messageInfo_Consignment proto.InternalMessageInfo

func (m *Consignment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Consignment) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Consignment) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Consignment) GetContainers() []*Contanier {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *Consignment) GetVesselId() string {
	if m != nil {
		return m.VesselId
	}
	return ""
}

// 单个集装箱
type Contanier struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId           string   `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Origin               string   `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Contanier) Reset()         { *m = Contanier{} }
func (m *Contanier) String() string { return proto.CompactTextString(m) }
func (*Contanier) ProtoMessage()    {}
func (*Contanier) Descriptor() ([]byte, []int) {
	return fileDescriptor_774f0b29a0c4f8e9, []int{1}
}

func (m *Contanier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contanier.Unmarshal(m, b)
}
func (m *Contanier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contanier.Marshal(b, m, deterministic)
}
func (m *Contanier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contanier.Merge(m, src)
}
func (m *Contanier) XXX_Size() int {
	return xxx_messageInfo_Contanier.Size(m)
}
func (m *Contanier) XXX_DiscardUnknown() {
	xxx_messageInfo_Contanier.DiscardUnknown(m)
}

var xxx_messageInfo_Contanier proto.InternalMessageInfo

func (m *Contanier) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Contanier) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *Contanier) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Contanier) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

// 托运结果
type Response struct {
	Created              bool         `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Consignment          *Consignment `protobuf:"bytes,2,opt,name=consignment,proto3" json:"consignment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_774f0b29a0c4f8e9, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetConsignment() *Consignment {
	if m != nil {
		return m.Consignment
	}
	return nil
}

func init() {
	proto.RegisterType((*Consignment)(nil), "Consignment")
	proto.RegisterType((*Contanier)(nil), "Contanier")
	proto.RegisterType((*Response)(nil), "Response")
}

func init() {
	proto.RegisterFile("proto/consignment.proto", fileDescriptor_774f0b29a0c4f8e9)
}

var fileDescriptor_774f0b29a0c4f8e9 = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xbd, 0x4e, 0x03, 0x31,
	0x10, 0x84, 0xb9, 0xfc, 0xdf, 0x1a, 0x81, 0x70, 0x41, 0x2c, 0x28, 0x38, 0x5d, 0x15, 0x51, 0x18,
	0x29, 0x3c, 0x01, 0x4a, 0x95, 0xd6, 0xa1, 0x47, 0xc1, 0x5e, 0x5d, 0x56, 0x22, 0xf6, 0xc9, 0x76,
	0xc2, 0xeb, 0xf0, 0xa8, 0xe8, 0x7c, 0x09, 0x18, 0x51, 0xce, 0xb7, 0xde, 0x9d, 0xd1, 0x18, 0xe6,
	0xad, 0x77, 0xd1, 0x3d, 0x69, 0x67, 0x03, 0x35, 0x76, 0x8f, 0x36, 0xca, 0x44, 0xea, 0xaf, 0x02,
	0xd8, 0xea, 0x97, 0xf2, 0x2b, 0x18, 0x90, 0x11, 0x45, 0x55, 0x2c, 0x4a, 0x35, 0x20, 0xc3, 0x2b,
	0x60, 0x06, 0x83, 0xf6, 0xd4, 0x46, 0x72, 0x56, 0x0c, 0xd2, 0x20, 0x47, 0xfc, 0x16, 0x26, 0x9f,
	0x48, 0xcd, 0x2e, 0x8a, 0x61, 0x55, 0x2c, 0xc6, 0xea, 0xa4, 0xf8, 0x23, 0x80, 0x76, 0x36, 0x6e,
	0xc9, 0xa2, 0x0f, 0x62, 0x54, 0x0d, 0x17, 0x6c, 0x09, 0x72, 0xd5, 0x21, 0x4b, 0xe8, 0x55, 0x36,
	0xe5, 0xf7, 0x50, 0x1e, 0x31, 0x04, 0xfc, 0x78, 0x23, 0x23, 0xc6, 0xc9, 0x63, 0xd6, 0x83, 0xb5,
	0xa9, 0xf7, 0x50, 0xfe, 0x6c, 0xfd, 0xcb, 0xf7, 0x00, 0x4c, 0x1f, 0x42, 0x74, 0x7b, 0xf4, 0xdd,
	0x6e, 0x9f, 0x0f, 0xce, 0x68, 0x6d, 0xba, 0x78, 0xce, 0x53, 0x43, 0x36, 0xc5, 0x2b, 0xd5, 0x49,
	0xf1, 0x39, 0x4c, 0x0f, 0xa1, 0x5f, 0x1a, 0xf5, 0x83, 0x4e, 0xae, 0x4d, 0xfd, 0x0a, 0x33, 0x85,
	0xa1, 0x75, 0x36, 0x20, 0x17, 0x30, 0xd5, 0x1e, 0xb7, 0x11, 0x7b, 0xcb, 0x99, 0x3a, 0x4b, 0x2e,
	0x81, 0x65, 0x65, 0x26, 0x5f, 0xb6, 0xbc, 0x94, 0x59, 0x95, 0x2a, 0x7f, 0xb0, 0x7c, 0x81, 0xeb,
	0xcd, 0x8e, 0xda, 0x96, 0x6c, 0xb3, 0x41, 0x7f, 0x24, 0x8d, 0x5c, 0xc2, 0xcd, 0x2a, 0x5d, 0xcb,
	0xfb, 0xff, 0x73, 0xe2, 0xae, 0x94, 0xe7, 0x28, 0xf5, 0xc5, 0xfb, 0x24, 0xfd, 0xd8, 0xf3, 0x77,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xc4, 0x25, 0xd5, 0xe7, 0xcc, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ShippingServiceClient is the client API for ShippingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShippingServiceClient interface {
	// 托运一批货物
	CreateConsignment(ctx context.Context, in *Consignment, opts ...grpc.CallOption) (*Response, error)
}

type shippingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShippingServiceClient(cc grpc.ClientConnInterface) ShippingServiceClient {
	return &shippingServiceClient{cc}
}

func (c *shippingServiceClient) CreateConsignment(ctx context.Context, in *Consignment, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/ShippingService/CreateConsignment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShippingServiceServer is the server API for ShippingService service.
type ShippingServiceServer interface {
	// 托运一批货物
	CreateConsignment(context.Context, *Consignment) (*Response, error)
}

// UnimplementedShippingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedShippingServiceServer struct {
}

func (*UnimplementedShippingServiceServer) CreateConsignment(ctx context.Context, req *Consignment) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateConsignment not implemented")
}

func RegisterShippingServiceServer(s *grpc.Server, srv ShippingServiceServer) {
	s.RegisterService(&_ShippingService_serviceDesc, srv)
}

func _ShippingService_CreateConsignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Consignment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingServiceServer).CreateConsignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShippingService/CreateConsignment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingServiceServer).CreateConsignment(ctx, req.(*Consignment))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShippingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ShippingService",
	HandlerType: (*ShippingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateConsignment",
			Handler:    _ShippingService_CreateConsignment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/consignment.proto",
}
